[buildPlans.IosevkaCustom]
family = "Infoc Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCustom.variants.design]
one = "no-base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "semi-open-serifless"
five = "upright-arched-serifless"
six = "straight-bar"
seven = "bend-serifless"
eight = "crossing"
nine = "straight-bar"
zero = "slashed"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "tailed"
g = "single-storey-serifless"
h = "straight-serifless"
i = "serifed"
j = "serifed"
k = "straight-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "bent-hook"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-serifless"
eszet = "sulzbacher-serifless"
lower-eth = "curly-bar"
capital-thorn = "serifless"
lower-thorn = "serifless"
lower-alpha = "crossing"
lower-beta = "standard"
capital-gamma = "serifless"
lower-gamma = "casual"
capital-delta = "straight"
lower-delta = "flat-top"
lower-eta = "serifless"
lower-theta = "oval"
lower-iota = "serifed-semi-tailed"
lower-kappa = "curly-serifless"
capital-lambda = "straight-serifless"
lower-lambda = "straight-turn"
lower-mu = "tailed-serifless"
lower-nu = "casual-serifed"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "semi-tailed"
lower-upsilon = "casual-serifed"
lower-phi = "cursive"
lower-chi = "semi-chancery-curly-serifless"
lower-psi = "short-neck-serifed"
partial-derivative = "curly-bar"
cyrl-a = "single-storey-tailed-serifed"
cyrl-ve = "standard-unilateral-serifed"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "symmetric-touching-top-left-and-bottom-right-serifed"
cyrl-ka = "symmetric-touching-top-left-and-bottom-right-serifed"
cyrl-el = "straight"
cyrl-em = "flat-bottom-motion-serifed"
cyrl-capital-en = "top-left-bottom-right-serifed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "straight-motion-serifed"
cyrl-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-che = "tailed"
cyrl-yeri = "corner"
cyrl-yery = "corner-tailed"
cyrl-capital-e = "unilateral-serifed"
cyrl-e = "unilateral-serifed"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-motion-serifed"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
ellipsis-density = "normal"
tilde = "low"
asterisk = "penta-high"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
guillemet = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "high"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "middle"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "javascript"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCustom.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCustom.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.IosevkaCustom.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"